services:
  - type: web
    name: laravel-app
    env: php
    region: oregon
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromService:
          name: laravel-db
          type: postgres
          property: host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        fromService:
          name: laravel-db
          type: postgres
          property: database
      - key: DB_USERNAME
        fromService:
          name: laravel-db
          type: postgres
          property: user
      - key: DB_PASSWORD
        fromService:
          name: laravel-db
          type: postgres
          property: password

databases:
  - name: laravel-db
    plan: free
    region: oregon
